
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sunilktk/configServerProperties.git
          refresh-rate: 1
          clone-on-start: true



eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost



logging:
  level:
    org:
      springframework: DEBUG


server:
  port: 8181

management:
  endpoints:
    web:
      exposure:
        include: refresh






